### ISSUE TITLE
Bootstrap dependency

### ISSUE THREAD

**Issue by msimonc** [flipbyte/formik-json-schema#26]
I'm trying to dynamically create Json from my MongoDB data to dynamically create forms, so thanks for your library!

I'm using Material UI in my app, but also could use styled-components,
can styling be made plugable?  Thanks!

**Comment by easeq** [comment]
There are few things that would allow you to customize the styling.

First of all, you can create your own template (check src/FieldTemplate.js) and pass that template along with each of your fields using the "template" key. 

You can also define your own HTML classes for pretty much all of the HTML elements at the element level in your schema object. And style them using an external css file. 

I am looking into other options for styling (especially styled-components) and once it's ready I'll publish it. 

I am open to suggestions as well.
