### ISSUE TITLE
Tab title overlaps select options

### ISSUE THREAD

**Issue by geseq** [flipbyte/formik-json-schema#31]
### Describe the bug

Tab titles overlap select options when the tab title is selected.

### To Reproduce

- Add a select with 3-4 options
- Add a tab container with 2 tabs immediately under it.
- Select the first tab.
- Click the select to show the options. The options will be overlapped by the tab title.

### Expected behavior

Options should not be overlapped.

**Comment by easeq** [comment]
Works now.
