### ISSUE TITLE
Code Editor cursor moves to the end on each character typed

### ISSUE THREAD

**Issue by earncef** [flipbyte/formik-json-schema#46]
### Describe the bug

Code Editor cursor moves to the end of the content on each character typed.

### To Reproduce

1. Go to the demo code editor.
2. paste some content.
3. try to edit anywhere but the end. Any keystroke moves the cursor to the end of the content.

### Expected behavior

It should be possible to edit the content

### Your environment

Demo

**Comment by earncef** [comment]
nvm, works with `autoCursor: false`

**Comment by easeq** [comment]
The config will look as follows:

```js
codeeditor: {
    ...
    attributes: {
        ...
        autoCursor: false,
    }
}
```
