### ISSUE TITLE
Only validate fields that are currently shown

### ISSUE THREAD

**Issue by andrewringler** [flipbyte/formik-json-schema#55]
I am making a field required by adding an attribute like `validation: [['string'], ['required']]` to my schema. I am making the field conditionally shown using an attribute like `showWhen: ['or', ['is', 'color', 'blue'], ['is', 'color', 'red]]`. It seems that even when the field is not shown, validation is being run, preventing me from submitting the form.

Would it make sense to only validate fields that are actually being shown? Or, alternatively, is there any way to include the `showWhen` logic in the `validation` statement?

**Comment by easeq** [comment]
It does make sense to validate just the visible fields, but at this time that is possible only by using the `when` condition provided by `yup`.

Following might work for your case:
 ```js
[['string'], ['when', 'color', {
        is: (value) => value === 'blue' || value == 'red',
        then: [['string'], ['required']]
}]]
```

**Comment by andrewringler** [comment]
Aaah. Perfect. Yes, that will work for me.

Thanks!

**Comment by andrewringler** [comment]
For anyone reading this thread if you are serializing your schema e.g. JSON.stringify and transporting it over the wire you will need to use some manual scheme to serialize your functions and then deserialize them when you read out your schema since Javascript functions are not valid JSON.

**Comment by ishaan-puniani** [comment]
I want it to be like JSON.stringify and transporting it over the wire. Not sure the simplest way to achieve it. still looking for support of this feature. 
@easeq  actually it makes sense if we have different sub forms to be filled in based on gender, dateofbirth and income range. and these sub forms might have required fields.

**Comment by easeq** [comment]
@ishaan-puniani I am not sure I understand your query. Would you be able to elaborate, preferably with an example?
