### ISSUE TITLE
Is it possible to overwrite FieldTemplate globally?

### ISSUE THREAD

**Issue by marmite22** [flipbyte/formik-json-schema#61]
### Is your feature request related to a problem? Please describe.

I'm trying to set up my own FieldTemplate for use on around all of our fields. (I need to add various components to the label amongst other things).

I can currently do this and load my template by specifying the template on each field.

### Describe the solution you'd like

Is there a way to specify the default FieldTemplate component globally (or at the form level) or something like that?

Thanks.

**Comment by easeq** [comment]
The feature doesn't exist currently. But i have been looking into solutions for adding global templates. For now, template key on each field is the only option.

**Comment by marmite22** [comment]
Cool thanks anyway. Would you like me to leave this open as a feature request or close it?

**Comment by easeq** [comment]
Let it be open. I'll close it once I've completed the feature.
