### ISSUE TITLE
[feat] Placeholder text functionality

### ISSUE THREAD

**Issue by gitdubz** [flipbyte/formik-json-schema#90]
### Is your feature request related to a problem? Please describe.

Currently, default functionality does not support having a placeholder text for input/text elements.
It would be useful to be able to provide a placeholder text 

### Describe the solution you'd like

From the example schema, something added like this would be great.

name: {
        name: 'name',
        placeholder: 'Full name', <-------- Add a placeholder property and apply it to the fields if supplied and relevant
        label: 'Name',
        type: 'field',
        renderer: 'text',
        fieldType: 'text',
        validation: [['string'], ['required'], ['min', 3]],
      },

### Describe alternatives you've considered

Using the "comment" property, which is sometimes used as helper text for the user.

**Comment by easeq** [comment]
You should be to add the placeholder property using the `attributes` object as shown below:

```js
name: {
   ...
   attributes: {
       ...,
       placeholder: "Fulle name",
   }
}
```
